# Generated by Django 5.0.4 on 2024-05-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='banner',
            field=models.ImageField(upload_to='image/site'),
        ),
    ]
