# Generated by Django 5.0.4 on 2024-05-02 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_statuc_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_item', to='orders.order'),
        ),
    ]
